# configs/data.yaml
# =================================================================
# DATA SOURCE CONFIGURATION
# =================================================================

# --- GLOBAL DATE CONTROL ---
global_date_window:
  start_date: "2000-01-01"
  end_date: "2025-12-31"

# --- MODEL TRAINING SPLITS ---
split:
  test_year: 2023
  validation_years: [2021, 2022, 2024, 2025]
  train_cutoff: "2020-12-31"

# --- SPATIAL BOUNDING BOX ---
car_bbox: [14.0, 2.0, 28.0, 11.5]

# =================================================================
# DATASETS
# =================================================================

# 1. CONFLICT & EVENTS
acled:
  local_file: "data/raw/acled.csv"
  country: "Central African Republic"

gdelt:
  bq_dataset: "gdelt-bq.gdeltv2.events"
  country_iso3: "CF"

# 2. ENVIRONMENTAL (Cloud APIs)
gee:
  project_id: "thesis-project-478503"
  collections:
    chirps: "UCSB-CHG/CHIRPS/DAILY"
    era5: "ECMWF/ERA5_LAND/HOURLY"
    modis: "MODIS/061/MCD43A4"
    viirs: "NASA/VIIRS/002/VNP46A2"

era5_cds:
  product: "reanalysis-era5-land"
  variables: ["2m_temperature", "2m_dewpoint_temperature"]
  hours: ["00:00", "06:00", "12:00", "18:00"]

# 3. SOCIO-POLITICAL
epr:
  geoepr_url: "https://icr.ethz.ch/data/epr/geoepr/GeoEPR-2021.geojson"
  core_url: "https://icr.ethz.ch/data/epr/core/EPR-2021.csv"

iom_dtm:
  api_endpoint: "https://api.dtm.iom.int/v3"
  country_name: "Central African Republic"

fews_net:
  ipc_url: "https://fdw.fews.net/api/ipcphase/"
  iso2: "CF"
  iso3: "CAF"
  markets_geojson_url: "https://fdw.fews.net/api/feature/?format=geojson&unit_set_version=3380"
  fallback_region_bundle: ""

wfp_vam:
  market_api_url: "https://api.vam.wfp.org/"
  country_iso3: "CAF"

# 4. INFRASTRUCTURE & GEOGRAPHY
world_bank_boundary:
  iso3: "CAF"
  url: "https://datacatalogfiles.worldpop.org/ddh-published-v2/0038272/5/DR0095369/World%20Bank%20Official%20Boundaries%20(GeoJSON)/World%20Bank%20Official%20Boundaries%20-%20Admin%200.geojson"
  filter_property: "ISO_A3"

admin_boundaries:
  admin1_path: "data/raw/wbgCAFadmin1.geojson" #labeled as admin1 in source from World Bank
  admin2_path: "data/raw/wbgCAFadmin2.geojson" #labeled as admin2 in source from World Bank
  admin3_path: "data/raw/wbgCAFadmin3.geojson" #labeled as admin2 in source from OCHA
  url: "https://datacatalog.worldbank.org/search/dataset/0038272/World-Bank-Official-Boundaries"


population:
  base_url_v2: "https://data.worldpop.org/GIS/Population/Global_2015_2030/R2025A"
  filename_template_v2: "caf_pop_{year}_CN_100m_R2025A_v1.tif"

copernicus:
  token_url: "https://identity.dataspace.copernicus.eu/auth/realms/CDSE/protocol/openid-connect/token"
  process_api_url: "https://sh.dataspace.copernicus.eu/api/v1/process"
  dem_instance: "COPERNICUS_90"

grip4:
  region3_url: "https://dataportaal.pbl.nl/downloads/GRIP4/GRIP4_Region3_vector_shp.zip"

hydrorivers:
  url: "https://data.hydrosheds.org/file/HydroRIVERS/HydroRIVERS_v10_af_shp.zip"
  min_stream_order: 3

osm:
  settlements_hdx_url: "https://data.humdata.org/dataset/27db004a-4f10-4046-a561-c0b0aea98ef0/resource/6d28d003-333c-442c-9d39-6903bb264814/download/caf_settlements_sigcaf.zip"

# 5. ECONOMY
ipis_mines:
  wfs_url: "https://geo.ipisresearch.be/geoserver/public/caf_mines_curated_all_opendata_p_ipis/wfs"
  type_name: "public:caf_mines_curated_all_opendata_p_ipis"

commodities:
  oil_series_id: "PET.RBRTE.D"
  ioda_entity_code: "CF"